# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App
# url: 'https://esitef-homologacao.softwareexpress.com.br/e-sitef-hml/Payment2?wsdl'
# default values
all:
  serverhost: 'https://vendorepuestos.com.ve'
  
  mailing:
    admin: "administracion@vendorepuestos.com.ve"
    from:
      email: "administracion@vendorepuestos.com.ve"
      fullname: "Vendorepuestos Administracion"
      
  esitef:
    merchant_key: 'E23267F07A37E02AC200F699C3500236B8D2FCE4DD3E9535A31C9BEB4C23406E'
    merchant_id: 'J317371879'
    url: 'https://esitef.softwareexpress.com.br/e-sitef/Payment2?wsdl'
    # Config DE PRUEBAS
#    merchant_key: 'A7B302A7F924C96CB54D320C82BF85D958CF31C67C053DE3A978B7218A9169EA'
#    merchant_id: 'vendorepuestos'
#    url: 'https://esitef-homologacao.softwareexpress.com.br/e-sitef-hml/Payment2?wsdl'
    connection_timeout: 50
    response_timeout: 50