<?php

/**
 * EstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoTable extends Doctrine_Table {
    
    public function getAlphabeticOrderQuery() {
        $q = Doctrine_Query::create()->from('Estado e');
        $q->addOrderBy('e.nombre ASC');
        
        return $q;
    }


    /**
     * Returns an instance of this class.
     *
     * @return object EstadoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Estado');
    }

}