<?php

/**
 * MedioPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedioPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedioPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedioPago');
    }
}