<?php

/**
 * PaymentOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentOrder');
    }
}