<?php

/**
 * PaymentOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PaymentOrder extends BasePaymentOrder {
    public function save(Doctrine_Connection $conn = null) {
        if ($this->getCardNumber()) {
            $cnum = $this->getCardNumber();
            $length = strlen($cnum) - 8;
            $first = substr($cnum, 0,4);
            $last = substr($cnum, -4);
            
            $this->setCardNumber($first . str_repeat('*', $length) . $last);
        }
        
        return parent::save($conn);
    }
}
