<?php

/**
 * Productos2401Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Productos2401Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Productos2401Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Productos2401');
    }
}