<?php

/**
 * ProductoEspejoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoEspejoTable extends ProductosTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoEspejoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoEspejo');
    }
}