<?php

/**
 * Productos2401
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Productos2401 extends BaseProductos2401
{

}