<?php

/**
 * Productos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Productos extends BaseProductos {

    public function getTarifa() {
        return Doctrine::getTable('Tarifas')->findOneBy('id', $this->getIdPaqueteUsuario());
    }
    
    public function checkPassword($password) {
        $hash = md5($this->getSalt().$password);
        
        return (strcmp($hash, $this->getPassword()) == 0);        
    }

}