<?php

/**
 * ProductoTemporalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoTemporalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoTemporalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoTemporal');
    }
}