<?php

/**
 * SalutacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalutacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalutacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Salutacion');
    }
}