<?php

/**
 * SubmenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubmenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubmenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Submenu');
    }
}