<?php

/**
 * Submenu2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Submenu2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Submenu2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Submenu2');
    }
}