<?php

/**
 * Tarifas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tarifas extends BaseTarifas {

    /**
     * Retorna el monto de una tarifa
     * @return float
     */
    public function getMonto() {
        return (float) $this->getTotalBs();
    }

}