<?php

/**
 * TarifasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TarifasTable extends Doctrine_Table {
    public function addByPrecioQuery($precio, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Tarifas t');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.condicion_desde <= ?', $precio);
        $q->andWhere($alias.'.condicion_hasta >= ?', $precio);
        
        return $q;
    }
    
    public function addByTipoQuery($tipo, Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()->from('Tarifas t');
        }
        
        $alias = $q->getRootAlias();
        
        $q->andWhere($alias.'.tipo = ? ', $tipo);
        
        return $q;
    }
    
    public function retrieveByPrecioAndTipo($precio, $tipo) {
        return $this->addByPrecioQuery($precio, $this->addByTipoQuery($tipo))->fetchOne();
    }

    /**
     * Returns an instance of this class.
     *
     * @return object TarifasTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tarifas');
    }

}