<?php

/**
 * TiendaVirtualTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiendaVirtualTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiendaVirtualTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiendaVirtual');
    }
}