<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/07/02 08:02:31
sfConfig::add(array(
  'app_serverhost' => 'https://vendorepuestos.com.ve',
  'app_mailing_admin' => 'administracion@vendorepuestos.com.ve',
  'app_mailing_from' => array (
  'email' => 'administracion@vendorepuestos.com.ve',
  'fullname' => 'Vendorepuestos Administracion',
),
  'app_esitef_merchant_key' => 'E23267F07A37E02AC200F699C3500236B8D2FCE4DD3E9535A31C9BEB4C23406E',
  'app_esitef_merchant_id' => 'J317371879',
  'app_esitef_url' => 'https://esitef.softwareexpress.com.br/e-sitef/Payment2?wsdl',
  'app_esitef_connection_timeout' => 50,
  'app_esitef_response_timeout' => 50,
));
