<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menu', 'doctrine');

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_categoria
 * @property string $nombre
 * @property integer $orden
 * @property string $logo
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method integer getIdCategoria()  Returns the current record's "id_categoria" value
 * @method string  getNombre()       Returns the current record's "nombre" value
 * @method integer getOrden()        Returns the current record's "orden" value
 * @method string  getLogo()         Returns the current record's "logo" value
 * @method Menu    setId()           Sets the current record's "id" value
 * @method Menu    setIdCategoria()  Sets the current record's "id_categoria" value
 * @method Menu    setNombre()       Sets the current record's "nombre" value
 * @method Menu    setOrden()        Sets the current record's "orden" value
 * @method Menu    setLogo()         Sets the current record's "logo" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('logo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}