<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Salutacion', 'doctrine');

/**
 * BaseSalutacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $texto
 * 
 * @method integer    getId()    Returns the current record's "id" value
 * @method string     getTexto() Returns the current record's "texto" value
 * @method Salutacion setId()    Sets the current record's "id" value
 * @method Salutacion setTexto() Sets the current record's "texto" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSalutacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('salutacion');
        $this->hasColumn('id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('texto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}