<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TiendaVirtual', 'doctrine');

/**
 * BaseTiendaVirtual
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $usuario
 * @property string $clave
 * @property string $rif
 * @property string $nombre_oficial
 * @property string $razon_social
 * @property string $telefono1
 * @property string $telefono2
 * @property string $pin
 * @property integer $id_estado
 * @property integer $id_ciudad
 * @property string $direccion
 * @property string $latitud
 * @property string $longitud
 * @property string $logo
 * @property string $foto1
 * @property string $foto2
 * @property string $foto3
 * @property string $pagina_web
 * @property string $facebook
 * @property string $twitter
 * @property string $email
 * @property string $descripcion
 * @property string $horario
 * @property string $datos_pago
 * @property string $datos_envio
 * @property string $datos_banco
 * @property string $color_titulo
 * @property string $color_fondo
 * @property string $color_contenido
 * @property string $persona_mantenimiento
 * @property string $telefono_mantenimiento
 * @property string $email_mantenimiento
 * @property timestamp $fecha_activacion
 * @property enum $activo
 * 
 * @method integer       getId()                     Returns the current record's "id" value
 * @method string        getUsuario()                Returns the current record's "usuario" value
 * @method string        getClave()                  Returns the current record's "clave" value
 * @method string        getRif()                    Returns the current record's "rif" value
 * @method string        getNombreOficial()          Returns the current record's "nombre_oficial" value
 * @method string        getRazonSocial()            Returns the current record's "razon_social" value
 * @method string        getTelefono1()              Returns the current record's "telefono1" value
 * @method string        getTelefono2()              Returns the current record's "telefono2" value
 * @method string        getPin()                    Returns the current record's "pin" value
 * @method integer       getIdEstado()               Returns the current record's "id_estado" value
 * @method integer       getIdCiudad()               Returns the current record's "id_ciudad" value
 * @method string        getDireccion()              Returns the current record's "direccion" value
 * @method string        getLatitud()                Returns the current record's "latitud" value
 * @method string        getLongitud()               Returns the current record's "longitud" value
 * @method string        getLogo()                   Returns the current record's "logo" value
 * @method string        getFoto1()                  Returns the current record's "foto1" value
 * @method string        getFoto2()                  Returns the current record's "foto2" value
 * @method string        getFoto3()                  Returns the current record's "foto3" value
 * @method string        getPaginaWeb()              Returns the current record's "pagina_web" value
 * @method string        getFacebook()               Returns the current record's "facebook" value
 * @method string        getTwitter()                Returns the current record's "twitter" value
 * @method string        getEmail()                  Returns the current record's "email" value
 * @method string        getDescripcion()            Returns the current record's "descripcion" value
 * @method string        getHorario()                Returns the current record's "horario" value
 * @method string        getDatosPago()              Returns the current record's "datos_pago" value
 * @method string        getDatosEnvio()             Returns the current record's "datos_envio" value
 * @method string        getDatosBanco()             Returns the current record's "datos_banco" value
 * @method string        getColorTitulo()            Returns the current record's "color_titulo" value
 * @method string        getColorFondo()             Returns the current record's "color_fondo" value
 * @method string        getColorContenido()         Returns the current record's "color_contenido" value
 * @method string        getPersonaMantenimiento()   Returns the current record's "persona_mantenimiento" value
 * @method string        getTelefonoMantenimiento()  Returns the current record's "telefono_mantenimiento" value
 * @method string        getEmailMantenimiento()     Returns the current record's "email_mantenimiento" value
 * @method timestamp     getFechaActivacion()        Returns the current record's "fecha_activacion" value
 * @method enum          getActivo()                 Returns the current record's "activo" value
 * @method TiendaVirtual setId()                     Sets the current record's "id" value
 * @method TiendaVirtual setUsuario()                Sets the current record's "usuario" value
 * @method TiendaVirtual setClave()                  Sets the current record's "clave" value
 * @method TiendaVirtual setRif()                    Sets the current record's "rif" value
 * @method TiendaVirtual setNombreOficial()          Sets the current record's "nombre_oficial" value
 * @method TiendaVirtual setRazonSocial()            Sets the current record's "razon_social" value
 * @method TiendaVirtual setTelefono1()              Sets the current record's "telefono1" value
 * @method TiendaVirtual setTelefono2()              Sets the current record's "telefono2" value
 * @method TiendaVirtual setPin()                    Sets the current record's "pin" value
 * @method TiendaVirtual setIdEstado()               Sets the current record's "id_estado" value
 * @method TiendaVirtual setIdCiudad()               Sets the current record's "id_ciudad" value
 * @method TiendaVirtual setDireccion()              Sets the current record's "direccion" value
 * @method TiendaVirtual setLatitud()                Sets the current record's "latitud" value
 * @method TiendaVirtual setLongitud()               Sets the current record's "longitud" value
 * @method TiendaVirtual setLogo()                   Sets the current record's "logo" value
 * @method TiendaVirtual setFoto1()                  Sets the current record's "foto1" value
 * @method TiendaVirtual setFoto2()                  Sets the current record's "foto2" value
 * @method TiendaVirtual setFoto3()                  Sets the current record's "foto3" value
 * @method TiendaVirtual setPaginaWeb()              Sets the current record's "pagina_web" value
 * @method TiendaVirtual setFacebook()               Sets the current record's "facebook" value
 * @method TiendaVirtual setTwitter()                Sets the current record's "twitter" value
 * @method TiendaVirtual setEmail()                  Sets the current record's "email" value
 * @method TiendaVirtual setDescripcion()            Sets the current record's "descripcion" value
 * @method TiendaVirtual setHorario()                Sets the current record's "horario" value
 * @method TiendaVirtual setDatosPago()              Sets the current record's "datos_pago" value
 * @method TiendaVirtual setDatosEnvio()             Sets the current record's "datos_envio" value
 * @method TiendaVirtual setDatosBanco()             Sets the current record's "datos_banco" value
 * @method TiendaVirtual setColorTitulo()            Sets the current record's "color_titulo" value
 * @method TiendaVirtual setColorFondo()             Sets the current record's "color_fondo" value
 * @method TiendaVirtual setColorContenido()         Sets the current record's "color_contenido" value
 * @method TiendaVirtual setPersonaMantenimiento()   Sets the current record's "persona_mantenimiento" value
 * @method TiendaVirtual setTelefonoMantenimiento()  Sets the current record's "telefono_mantenimiento" value
 * @method TiendaVirtual setEmailMantenimiento()     Sets the current record's "email_mantenimiento" value
 * @method TiendaVirtual setFechaActivacion()        Sets the current record's "fecha_activacion" value
 * @method TiendaVirtual setActivo()                 Sets the current record's "activo" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiendaVirtual extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tienda_virtual');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('clave', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('rif', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('nombre_oficial', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('razon_social', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('telefono1', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('telefono2', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('pin', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('id_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ciudad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('latitud', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('longitud', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('logo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto1', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto2', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto3', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('pagina_web', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('facebook', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('twitter', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('horario', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('datos_pago', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('datos_envio', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('datos_banco', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('color_titulo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('color_fondo', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('color_contenido', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('persona_mantenimiento', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('telefono_mantenimiento', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('email_mantenimiento', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fecha_activacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('activo', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}