<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MedioEnvio', 'doctrine');

/**
 * BaseMedioEnvio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * 
 * @method integer    getId()     Returns the current record's "id" value
 * @method string     getNombre() Returns the current record's "nombre" value
 * @method MedioEnvio setId()     Sets the current record's "id" value
 * @method MedioEnvio setNombre() Sets the current record's "nombre" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedioEnvio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('medio_envio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}