<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Noticias', 'doctrine');

/**
 * BaseNoticias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $titulo
 * @property string $sumario
 * @property string $texto
 * @property string $foto
 * @property string $link
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method string   getTitulo()  Returns the current record's "titulo" value
 * @method string   getSumario() Returns the current record's "sumario" value
 * @method string   getTexto()   Returns the current record's "texto" value
 * @method string   getFoto()    Returns the current record's "foto" value
 * @method string   getLink()    Returns the current record's "link" value
 * @method Noticias setId()      Sets the current record's "id" value
 * @method Noticias setTitulo()  Sets the current record's "titulo" value
 * @method Noticias setSumario() Sets the current record's "sumario" value
 * @method Noticias setTexto()   Sets the current record's "texto" value
 * @method Noticias setFoto()    Sets the current record's "foto" value
 * @method Noticias setLink()    Sets the current record's "link" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNoticias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('noticias');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sumario', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('foto', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}