<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Submenu', 'doctrine');

/**
 * BaseSubmenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_categoria
 * @property integer $id_menu
 * @property string $nombre
 * @property integer $orden
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method integer getIdCategoria()  Returns the current record's "id_categoria" value
 * @method integer getIdMenu()       Returns the current record's "id_menu" value
 * @method string  getNombre()       Returns the current record's "nombre" value
 * @method integer getOrden()        Returns the current record's "orden" value
 * @method Submenu setId()           Sets the current record's "id" value
 * @method Submenu setIdCategoria()  Sets the current record's "id_categoria" value
 * @method Submenu setIdMenu()       Sets the current record's "id_menu" value
 * @method Submenu setNombre()       Sets the current record's "nombre" value
 * @method Submenu setOrden()        Sets the current record's "orden" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubmenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('submenu');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_menu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}