<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Submenu2', 'doctrine');

/**
 * BaseSubmenu2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_categoria
 * @property integer $id_menu
 * @property integer $id_submenu
 * @property string $nombre
 * @property integer $orden
 * 
 * @method integer  getId()           Returns the current record's "id" value
 * @method integer  getIdCategoria()  Returns the current record's "id_categoria" value
 * @method integer  getIdMenu()       Returns the current record's "id_menu" value
 * @method integer  getIdSubmenu()    Returns the current record's "id_submenu" value
 * @method string   getNombre()       Returns the current record's "nombre" value
 * @method integer  getOrden()        Returns the current record's "orden" value
 * @method Submenu2 setId()           Sets the current record's "id" value
 * @method Submenu2 setIdCategoria()  Sets the current record's "id_categoria" value
 * @method Submenu2 setIdMenu()       Sets the current record's "id_menu" value
 * @method Submenu2 setIdSubmenu()    Sets the current record's "id_submenu" value
 * @method Submenu2 setNombre()       Sets the current record's "nombre" value
 * @method Submenu2 setOrden()        Sets the current record's "orden" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubmenu2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('submenu2');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_menu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_submenu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}