<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tarifas', 'doctrine');

/**
 * BaseTarifas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property decimal $total_bs
 * @property integer $cantidad_productos
 * @property enum $habilitar
 * @property integer $duracion_dias
 * @property enum $tipo
 * @property integer $condicion_desde
 * @property integer $condicion_hasta
 * 
 * @method integer getId()                 Returns the current record's "id" value
 * @method string  getNombre()             Returns the current record's "nombre" value
 * @method decimal getTotalBs()            Returns the current record's "total_bs" value
 * @method integer getCantidadProductos()  Returns the current record's "cantidad_productos" value
 * @method enum    getHabilitar()          Returns the current record's "habilitar" value
 * @method integer getDuracionDias()       Returns the current record's "duracion_dias" value
 * @method enum    getTipo()               Returns the current record's "tipo" value
 * @method integer getCondicionDesde()     Returns the current record's "condicion_desde" value
 * @method integer getCondicionHasta()     Returns the current record's "condicion_hasta" value
 * @method Tarifas setId()                 Sets the current record's "id" value
 * @method Tarifas setNombre()             Sets the current record's "nombre" value
 * @method Tarifas setTotalBs()            Sets the current record's "total_bs" value
 * @method Tarifas setCantidadProductos()  Sets the current record's "cantidad_productos" value
 * @method Tarifas setHabilitar()          Sets the current record's "habilitar" value
 * @method Tarifas setDuracionDias()       Sets the current record's "duracion_dias" value
 * @method Tarifas setTipo()               Sets the current record's "tipo" value
 * @method Tarifas setCondicionDesde()     Sets the current record's "condicion_desde" value
 * @method Tarifas setCondicionHasta()     Sets the current record's "condicion_hasta" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarifas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarifas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('total_bs', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('cantidad_productos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('habilitar', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('duracion_dias', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'enum', 7, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'tienda',
              1 => 'persona',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('condicion_desde', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('condicion_hasta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}