<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Productos', 'doctrine');

/**
 * BaseProductos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $titulo
 * @property string $subtitulo
 * @property string $foto1
 * @property string $foto2
 * @property string $foto3
 * @property string $descripcion
 * @property integer $id_estado
 * @property integer $id_ciudad
 * @property string $condicion
 * @property decimal $precio
 * @property date $vence
 * @property integer $id_categoria
 * @property integer $id_menu
 * @property integer $id_submenu
 * @property integer $id_submenu2
 * @property integer $id_paquete_usuario
 * @property enum $usuario_tienda
 * @property integer $id_usuario_tienda
 * @property timestamp $fecha_publicacion
 * @property integer $visitas
 * @property timestamp $ultima_visita
 * @property enum $oferta_dia
 * @property string $salt
 * @property string $password
 * @property Usuario $Usuario
 * @property Estado $Estado
 * @property Ciudad $Ciudad
 * @property ProductoTemporal $UserProfile
 * 
 * @method integer          getId()                 Returns the current record's "id" value
 * @method string           getTitulo()             Returns the current record's "titulo" value
 * @method string           getSubtitulo()          Returns the current record's "subtitulo" value
 * @method string           getFoto1()              Returns the current record's "foto1" value
 * @method string           getFoto2()              Returns the current record's "foto2" value
 * @method string           getFoto3()              Returns the current record's "foto3" value
 * @method string           getDescripcion()        Returns the current record's "descripcion" value
 * @method integer          getIdEstado()           Returns the current record's "id_estado" value
 * @method integer          getIdCiudad()           Returns the current record's "id_ciudad" value
 * @method string           getCondicion()          Returns the current record's "condicion" value
 * @method decimal          getPrecio()             Returns the current record's "precio" value
 * @method date             getVence()              Returns the current record's "vence" value
 * @method integer          getIdCategoria()        Returns the current record's "id_categoria" value
 * @method integer          getIdMenu()             Returns the current record's "id_menu" value
 * @method integer          getIdSubmenu()          Returns the current record's "id_submenu" value
 * @method integer          getIdSubmenu2()         Returns the current record's "id_submenu2" value
 * @method integer          getIdPaqueteUsuario()   Returns the current record's "id_paquete_usuario" value
 * @method enum             getUsuarioTienda()      Returns the current record's "usuario_tienda" value
 * @method integer          getIdUsuarioTienda()    Returns the current record's "id_usuario_tienda" value
 * @method timestamp        getFechaPublicacion()   Returns the current record's "fecha_publicacion" value
 * @method integer          getVisitas()            Returns the current record's "visitas" value
 * @method timestamp        getUltimaVisita()       Returns the current record's "ultima_visita" value
 * @method enum             getOfertaDia()          Returns the current record's "oferta_dia" value
 * @method string           getSalt()               Returns the current record's "salt" value
 * @method string           getPassword()           Returns the current record's "password" value
 * @method Usuario          getUsuario()            Returns the current record's "Usuario" value
 * @method Estado           getEstado()             Returns the current record's "Estado" value
 * @method Ciudad           getCiudad()             Returns the current record's "Ciudad" value
 * @method ProductoTemporal getUserProfile()        Returns the current record's "UserProfile" value
 * @method Productos        setId()                 Sets the current record's "id" value
 * @method Productos        setTitulo()             Sets the current record's "titulo" value
 * @method Productos        setSubtitulo()          Sets the current record's "subtitulo" value
 * @method Productos        setFoto1()              Sets the current record's "foto1" value
 * @method Productos        setFoto2()              Sets the current record's "foto2" value
 * @method Productos        setFoto3()              Sets the current record's "foto3" value
 * @method Productos        setDescripcion()        Sets the current record's "descripcion" value
 * @method Productos        setIdEstado()           Sets the current record's "id_estado" value
 * @method Productos        setIdCiudad()           Sets the current record's "id_ciudad" value
 * @method Productos        setCondicion()          Sets the current record's "condicion" value
 * @method Productos        setPrecio()             Sets the current record's "precio" value
 * @method Productos        setVence()              Sets the current record's "vence" value
 * @method Productos        setIdCategoria()        Sets the current record's "id_categoria" value
 * @method Productos        setIdMenu()             Sets the current record's "id_menu" value
 * @method Productos        setIdSubmenu()          Sets the current record's "id_submenu" value
 * @method Productos        setIdSubmenu2()         Sets the current record's "id_submenu2" value
 * @method Productos        setIdPaqueteUsuario()   Sets the current record's "id_paquete_usuario" value
 * @method Productos        setUsuarioTienda()      Sets the current record's "usuario_tienda" value
 * @method Productos        setIdUsuarioTienda()    Sets the current record's "id_usuario_tienda" value
 * @method Productos        setFechaPublicacion()   Sets the current record's "fecha_publicacion" value
 * @method Productos        setVisitas()            Sets the current record's "visitas" value
 * @method Productos        setUltimaVisita()       Sets the current record's "ultima_visita" value
 * @method Productos        setOfertaDia()          Sets the current record's "oferta_dia" value
 * @method Productos        setSalt()               Sets the current record's "salt" value
 * @method Productos        setPassword()           Sets the current record's "password" value
 * @method Productos        setUsuario()            Sets the current record's "Usuario" value
 * @method Productos        setEstado()             Sets the current record's "Estado" value
 * @method Productos        setCiudad()             Sets the current record's "Ciudad" value
 * @method Productos        setUserProfile()        Sets the current record's "UserProfile" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('productos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('subtitulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('foto1', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto2', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto3', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('id_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ciudad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('condicion', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('precio', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('vence', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_menu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_submenu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_submenu2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_paquete_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_tienda', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '1',
              1 => '2',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_usuario_tienda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_publicacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('visitas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ultima_visita', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('oferta_dia', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('salt', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'id_usuario_tienda',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Estado', array(
             'local' => 'id_estado',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Ciudad', array(
             'local' => 'id_ciudad',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('ProductoTemporal as UserProfile', array(
             'local' => 'id',
             'foreign' => 'producto_id'));
    }
}