<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductoTemporal', 'doctrine');

/**
 * BaseProductoTemporal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $productos_id
 * @property integer $producto_id
 * @property string $titulo
 * @property string $subtitulo
 * @property string $foto1
 * @property string $foto2
 * @property string $foto3
 * @property string $descripcion
 * @property integer $id_estado
 * @property integer $id_ciudad
 * @property string $condicion
 * @property decimal $precio
 * @property date $vence
 * @property integer $id_categoria
 * @property integer $id_menu
 * @property integer $id_submenu
 * @property integer $id_submenu2
 * @property integer $id_paquete_usuario
 * @property enum $usuario_tienda
 * @property integer $id_usuario_tienda
 * @property timestamp $fecha_publicacion
 * @property integer $visitas
 * @property timestamp $ultima_visita
 * @property enum $oferta_dia
 * @property string $salt
 * @property string $password
 * @property Productos $Producto
 * @property Usuario $Usuario
 * @property Estado $Estado
 * @property Ciudad $Ciudad
 * 
 * @method integer          getProductosId()        Returns the current record's "productos_id" value
 * @method integer          getProductoId()         Returns the current record's "producto_id" value
 * @method string           getTitulo()             Returns the current record's "titulo" value
 * @method string           getSubtitulo()          Returns the current record's "subtitulo" value
 * @method string           getFoto1()              Returns the current record's "foto1" value
 * @method string           getFoto2()              Returns the current record's "foto2" value
 * @method string           getFoto3()              Returns the current record's "foto3" value
 * @method string           getDescripcion()        Returns the current record's "descripcion" value
 * @method integer          getIdEstado()           Returns the current record's "id_estado" value
 * @method integer          getIdCiudad()           Returns the current record's "id_ciudad" value
 * @method string           getCondicion()          Returns the current record's "condicion" value
 * @method decimal          getPrecio()             Returns the current record's "precio" value
 * @method date             getVence()              Returns the current record's "vence" value
 * @method integer          getIdCategoria()        Returns the current record's "id_categoria" value
 * @method integer          getIdMenu()             Returns the current record's "id_menu" value
 * @method integer          getIdSubmenu()          Returns the current record's "id_submenu" value
 * @method integer          getIdSubmenu2()         Returns the current record's "id_submenu2" value
 * @method integer          getIdPaqueteUsuario()   Returns the current record's "id_paquete_usuario" value
 * @method enum             getUsuarioTienda()      Returns the current record's "usuario_tienda" value
 * @method integer          getIdUsuarioTienda()    Returns the current record's "id_usuario_tienda" value
 * @method timestamp        getFechaPublicacion()   Returns the current record's "fecha_publicacion" value
 * @method integer          getVisitas()            Returns the current record's "visitas" value
 * @method timestamp        getUltimaVisita()       Returns the current record's "ultima_visita" value
 * @method enum             getOfertaDia()          Returns the current record's "oferta_dia" value
 * @method string           getSalt()               Returns the current record's "salt" value
 * @method string           getPassword()           Returns the current record's "password" value
 * @method Productos        getProducto()           Returns the current record's "Producto" value
 * @method Usuario          getUsuario()            Returns the current record's "Usuario" value
 * @method Estado           getEstado()             Returns the current record's "Estado" value
 * @method Ciudad           getCiudad()             Returns the current record's "Ciudad" value
 * @method ProductoTemporal setProductosId()        Sets the current record's "productos_id" value
 * @method ProductoTemporal setProductoId()         Sets the current record's "producto_id" value
 * @method ProductoTemporal setTitulo()             Sets the current record's "titulo" value
 * @method ProductoTemporal setSubtitulo()          Sets the current record's "subtitulo" value
 * @method ProductoTemporal setFoto1()              Sets the current record's "foto1" value
 * @method ProductoTemporal setFoto2()              Sets the current record's "foto2" value
 * @method ProductoTemporal setFoto3()              Sets the current record's "foto3" value
 * @method ProductoTemporal setDescripcion()        Sets the current record's "descripcion" value
 * @method ProductoTemporal setIdEstado()           Sets the current record's "id_estado" value
 * @method ProductoTemporal setIdCiudad()           Sets the current record's "id_ciudad" value
 * @method ProductoTemporal setCondicion()          Sets the current record's "condicion" value
 * @method ProductoTemporal setPrecio()             Sets the current record's "precio" value
 * @method ProductoTemporal setVence()              Sets the current record's "vence" value
 * @method ProductoTemporal setIdCategoria()        Sets the current record's "id_categoria" value
 * @method ProductoTemporal setIdMenu()             Sets the current record's "id_menu" value
 * @method ProductoTemporal setIdSubmenu()          Sets the current record's "id_submenu" value
 * @method ProductoTemporal setIdSubmenu2()         Sets the current record's "id_submenu2" value
 * @method ProductoTemporal setIdPaqueteUsuario()   Sets the current record's "id_paquete_usuario" value
 * @method ProductoTemporal setUsuarioTienda()      Sets the current record's "usuario_tienda" value
 * @method ProductoTemporal setIdUsuarioTienda()    Sets the current record's "id_usuario_tienda" value
 * @method ProductoTemporal setFechaPublicacion()   Sets the current record's "fecha_publicacion" value
 * @method ProductoTemporal setVisitas()            Sets the current record's "visitas" value
 * @method ProductoTemporal setUltimaVisita()       Sets the current record's "ultima_visita" value
 * @method ProductoTemporal setOfertaDia()          Sets the current record's "oferta_dia" value
 * @method ProductoTemporal setSalt()               Sets the current record's "salt" value
 * @method ProductoTemporal setPassword()           Sets the current record's "password" value
 * @method ProductoTemporal setProducto()           Sets the current record's "Producto" value
 * @method ProductoTemporal setUsuario()            Sets the current record's "Usuario" value
 * @method ProductoTemporal setEstado()             Sets the current record's "Estado" value
 * @method ProductoTemporal setCiudad()             Sets the current record's "Ciudad" value
 * 
 * @package    ptoventavr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductoTemporal extends Productos
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('producto_temporal');
        $this->hasColumn('productos_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('subtitulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('foto1', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto2', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('foto3', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('id_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_ciudad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('condicion', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('precio', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('vence', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_categoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_menu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_submenu', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_submenu2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_paquete_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_tienda', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '1',
              1 => '2',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_usuario_tienda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_publicacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('visitas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ultima_visita', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('oferta_dia', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => '0',
              1 => '1',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('salt', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Productos as Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Usuario', array(
             'local' => 'id_usuario_tienda',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Estado', array(
             'local' => 'id_estado',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Ciudad', array(
             'local' => 'id_ciudad',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}