<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/07/02 08:04:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=vendorepuestos.db.9355050.hostedresource.com;dbname=vendorepuestos',
  'username' => 'vendorepuestos',
  'password' => 'vendo@Admin12',
  'name' => 'doctrine',
)),);
